apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-dracarys-app-ingress
  namespace: stg
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: app.stg.lkravi.me
      http:
        paths:
          - backend:
              service: 
                name: release-name-dracarys-app
                port: 
                  number: 80
            path: /
            pathType: Prefix