apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-stg
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: stg
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/igd-hackathon/dracarys-workloads.git
    targetRevision: main
    path: teams/team-a/stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true