apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-cd-argocd-server-ingress
  namespace: configs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: argocd.lkravi.me
      http:
        paths:
          - backend:
              service: 
                name: argo-cd-argocd-server
                port: 
                  number: 443
            path: /
            pathType: Prefix