apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: configs
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/igd-hackathon/dracarys-workloads.git
    targetRevision: main
    path: configs/ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true